import Head from "next/head";
import Header from "../components/Header";
import Banner from "../components/Banner";
import https from "https";
import SmallCard from "../components/SmallCard";
import MediumCard from "../components/MediumCard";
import LargeCard from "../components/LargeCard";
import { Footer } from "../components/Footer";

const httpsAgent = new https.Agent({ rejectUnauthorized: false });

export default function Home({ exploreData, cardsData }) {
  console.log(exploreData);
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Banner />
      <main className="max-w-7xl mx-auto px-8 sm:px-16 ">
        <section className="pt-6 ">
          <h2 className="text-4xl font-semibold pb-5">explorar mais</h2>
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 ">
            {exploreData?.map((item) => (
              <SmallCard key={Date.now().toString()} item={item} />
            ))}
          </div>
        </section>
        <section>
          <h2 className="text-4xl font-semibold py-8">
            Viva em qualquer lugar
          </h2>
          <div className="flex space-x-3 overflow-scroll scrollbar-hide p-3 -ml-3">
            {cardsData?.map((card) => (
              <MediumCard key={Date.now().toString()} card={card} />
            ))}
          </div>
        </section>
        <LargeCard
          img="https://links.papareact.com/4cj"
          title="Viaje para ser feliz"
          description="Seja livre e aproveite a viagem"
          buttonText="Busque expiração"
        />
      </main>
      <Footer />
    </div>
  );
}
export async function getStaticProps() {
  const exploreData = await fetch("https://links.papareact.com/pyp", {
    agent: httpsAgent,
  }).then(async (res) => await res.json());

  const cardsData = await fetch("https://links.papareact.com/zp1", {
    agent: httpsAgent,
  }).then(async (res) => await res.json());

  return {
    props: {
      exploreData,
      cardsData,
    },
  };
}
